### ISSUE TITLE
question about miRNA metadata

### ISSUE THREAD

**Issue by lpantano** [Sage-Bionetworks/pcbc_c4_analysis#13] opened 2015-02-26 20:40 UTC
Hi,

I am moving to use wiki Tables as you suggested in the meeting. If I do this:

```
# Get metadata
metadata_id = "syn3219876"
metadata_obj = synTableQuery(paste('SELECT * FROM',metadata_id,sep=' '))
ALL_USED_OBJ[length(ALL_USED_OBJ)+1] = METADATA_OBJ;
metadata = metadata_obj@values
row.names(metadata) = metadata$UID
```

I got an error for duplicated samples UID? is that possible?

```
Error in `row.names<-.data.frame`(`*tmp*`, value = c("CD34-control-DMSO.139.7.40",  : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names': ‘SC11-016DE.134.7.1’, ‘SC11-016DE.416.2.34’, ‘SC12-025EB.181+185+187.5+1+6.1’, ‘SC12-025EB.416.2.29’ 
```

One example:

```
 C4_Cell_Line_ID Replicate ReplicateIncomplete biologicalSampleName Diffname_short                UID run lane index     QC pass_qc
1        SC11-016         A                               SC11-016DE             DE SC11-016DE.134.7.1 134    7     1 FAILED   FALSE
2        SC11-016         A                               SC11-016DE             DE SC11-016DE.134.7.1 134    7     1 FAILED   FALSE
  exclude     ExcludeReason CellDiffState comment SampleType SampleTypeIncomplete SampleTypeNotes ReplicateNotes  ThawDate
1    TRUE replicate-exclude        DE-bad  DE-bad         DE                   DE                                 1/4/2012
2    TRUE replicate-exclude        DE-bad  DE-bad         DE                   DE                                6/21/2013
  ThawDateNotes PassageAtThawNotes DateRNAHarvested RNAHarvestedNotes DatemRNAExtracted DatemRNAExtractedNotes DatemiRNAextracted
1            NA                            3/4/2012                NA         3/15/2012                     NA          3/15/2012
2            NA                           7/26/2013                NA        12/11/2013                     NA         12/10/2013
```

Is like the same sample twice. 

so, should I use this table? is this expected?

thanks!

**Comment by kdaily** [comment] 2015-02-26 21:27
Glad you noticed that too. I have these two samples as 'duplicates':

`SC11-016DE`, `SC12-025EB`

The issue is there are duplicates in the sample processing table. See this query:

[Duplicates in Sample Processing Table](https://www.synapse.org/#!Synapse:syn3131513/tables/query/eyJsaW1pdCI6MjUsICJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjMxMzE1MTMgV0hFUkUgYmlvbG9naWNhbFNhbXBsZU5hbWUgaW4gKCdTQzExLTAxNkRFJywgJ1NDMTItMDI1RUInKSIsICJpc0NvbnNpc3RlbnQiOnRydWUsICJvZmZzZXQiOjB9)

It seems these biological samples were processed multiple times (look at the extracted dates). As long as you aren't using columns related to dates of processing, it's safe to just 'unique' them. I'm working on contacting the person in charge to resolve it!

**Comment by kdaily** [comment] 2015-02-26 21:28
I'm making some notes regarding the metadata here:

https://www.synapse.org/#!Synapse:syn1773109/wiki/93226

**Comment by kdaily** [comment] 2015-02-26 21:36
I should also note that in your example, both of these failed QC...

**Comment by kdaily** [comment] 2015-03-07 00:01
I haven't forgotten this; need to match up run number with date to see if everything works out.

**Comment by kdaily** [comment] 2015-07-17 22:45
Fixed in things tangential to this issue.

**Closed as completed by kdaily** 2015-07-17 22:45 UTC
Labels: question
